### ISSUE TITLE
Is this production ready?

### ISSUE THREAD

**Issue by Attacler** [Vultwo/eBoekhouden-Node#1]
Hi there,

I saw that the package is currently under construction so i was wondering when it would be ready for production.

**Comment by Vultwo** [comment]
Hi,

Sorry for the slow response. The code isn't production ready at the moment as some functions still have to be implemented.
I actually didn't need the package anymore for my personal use. So I don't know if I will ever continue working on it.
If I have to take a wild estimate it would be about a year.
Some functions are functioning though. Feel free to dive into the code and take the functions you need.
